'use client';

export {
    ArrowRight,
    Clock,
    Lightning,
    Desktop,
    FileText,
    ShieldCheck,
    PaintBrush,
    Gear,
    GameController,
    Headset,
    PaperPlaneRight, // For Footer
    FacebookLogo,
    TwitterLogo,
    InstagramLogo,
    YoutubeLogo,
    Envelope,
    Phone,
    MapPin,
    CreditCard,
    Truck,
    Check,
    Star,
    ShoppingCart,
    Heart,
    User,
    List,
    X,
    CaretDown,
    Package,
    SignOut,
    Globe,
    ChatCircleDots,
    Gift,
    LockKey,
    Wrench,
    MagnifyingGlass,
    Question
} from '@phosphor-icons/react';
