'use client';

// Re-export Lucide icons with convenient aliases
// These replace the previous Phosphor icon exports
export {
    ArrowRight,
    RotateCcw as ArrowCounterClockwise,
    MessageCircle as ChatCircle,
    Clock,
    CloudDownload as CloudArrowDown,
    Cookie,
    CreditCard,
    Database,
    Monitor as Desktop,
    Mail as Envelope,
    Eye,
    Facebook as FacebookLogo,
    FileText,
    Gamepad2 as GameController,
    Gavel,
    Settings as Gear,
    Gift,
    Globe,
    MessageCircleMore as ChatCircleDots,
    Headphones as Headset,
    Heart,
    Info,
    Instagram as InstagramLogo,
    Zap as Lightning,
    List,
    Lock,
    KeyRound as LockKey,
    Search as MagnifyingGlass,
    MapPin,
    Package,
    Paintbrush as PaintBrush,
    Send as PaperPlaneRight,
    SendHorizontal as PaperPlaneTilt,
    Phone,
    HelpCircle as Question,
    Scale as Scales,
    ShieldCheck,
    ShoppingCart,
    LogOut as SignOut,
    Star,
    Check,
    CheckCircle2 as CheckCircle,
    XCircle,
    Truck,
    Twitter as TwitterLogo,
    User,
    UserCircle,
    AlertTriangle as Warning,
    MessageCircle as WhatsappLogo,
    Wrench,
    X,
    ChevronDown as CaretDown,
    Youtube as YoutubeLogo
} from 'lucide-react';
